### ISSUE TITLE
radeon developer panel in RGP V1.12 crashes when lauching application

### ISSUE THREAD

**Issue by delphifirst** [GPUOpen-Tools/radeon_gpu_profiler#63] opened 2022-03-02 13:10 UTC
I downloaded RGP V1.12 and wanted to profile my application. But Radeon Developer Panel crashed without any message immediately when I lauch my application.

However, I tried V1.11 and it works fine.

**Comment by chesik-amd** [comment] 2022-03-02 13:16
Sorry to hear you're having problems with Radeon Developer Panel.  Can you try using the Profiling workflow (rather than the Default workflow) in RDP?  Are you able to launch your application with just the Profiling workflow?

**Comment by chesik-amd** [comment] 2022-03-02 13:29
OK, thanks for trying. Can you share the RDP log file? It can be found in %APPDATA%/RadeonDeveloperPanel/log.txt. I can ask the RDP team to take a look at it to see if there are any hints as to what is going wrong.

**Comment by chesik-amd** [comment] 2022-03-02 18:44
Thanks for sharing this.  It looks like RDP was unable to query the system info. The speculation is that something that gets communicated via the system info (perhaps the hostname?) has a non-ASCII character contained in it, and that is causing the issue.

Right after launching RDP but before launching your app, if you press Ctrl-L in RDP, do you see data in the "System Info" tab? Or is it blank? If there is data present, are there any values that contain non-ASCII characters?

**Comment by delphifirst** [comment] 2022-03-03 01:55
In RDP V1.12, the "System Info" tab is blank.

I also tried in RDP V1.11, the "System Info"  tab has content like this. It seems there is no non-ASCII character:
`
{
    "client": {
        "value": {
            "branch": "ddLegacy",
            "busVersion": 1011,
            "description": "ddRouter Internal Client",
            "id": 2730,
            "interfaceVersion": {
                "available": 42,
                "supported": 42
            },
            "libraryVersion": "v21.05.25",
            "name": "RadeonDeveloperPanel.exe",
            "platform": "Windows User Mode 64-bit",
            "processId": 12448,
            "protocols": [
                "transfer",
                {
                    "maxVersion": 2,
                    "minVersion": 1
                },
                "uri",
                {
                    "maxVersion": 3,
                    "minVersion": 1
                },
                "etw",
                {
                    "maxVersion": 3,
                    "minVersion": 3
                }
            ],
            "status": {
                "developerModeEnabled": false,
                "deviceHaltOnConnectEnabled": false,
                "gpuCrashEnabled": false,
                "pipelineDumpsEnabled": false,
                "platformHaltOnConnectEnabled": false
            },
            "transport": "Named Pipe",
            "type": "Server"
        },
        "version": 1
    },
    "stats": {
        "value": {
            "timestamp": {
                "ticks": 510132585786,
                "ticksPerSecond": 10000000
            }
        },
        "version": 1
    },
    "system": {
        "value": {
            "cpu": {
                "timestampFrequency": 10000000
            },
            "devdriver": {
                "GPUOPEN_CLIENT_INTERFACE_MAJOR_VERSION": 42,
                "tag": "v21.05.25"
            },
            "driver": {
                "packagingVersion": "21.10.2"
            },
            "gpus": [
                {
                    "asic": {
                        "engineClockHz": {
                            "max": 1600000000,
                            "min": 200000000
                        },
                        "gpuCounterFreq": 100000000,
                        "gpuIndex": 0,
                        "ids": {
                            "device": 5688,
                            "eRev": 161,
                            "family": 142,
                            "gfxEngine": 13,
                            "revision": 211
                        }
                    },
                    "bigSw": {
                        "major": 2021,
                        "minor": 0,
                        "misc": 0
                    },
                    "memory": {
                        "bandwidth": 42656000000,
                        "busBitWidth": 128,
                        "excludedVaRanges": [
                            {
                                "base": 0,
                                "size": 4096
                            }
                        ],
                        "heaps": {
                            "invisible": {
                                "physAddr": 268435456,
                                "size": 268435456
                            },
                            "local": {
                                "physAddr": 0,
                                "size": 268435456
                            }
                        },
                        "memClockHz": {
                            "max": 1333000000,
                            "min": 400000000
                        },
                        "memOpsPerClock": 2,
                        "type": "Ddr4"
                    },
                    "name": "AMD Radeon(TM) Graphics",
                    "pci": {
                        "bus": 5,
                        "device": 0,
                        "function": 0
                    }
                }
            ],
            "os": {
                "desc": "18362.1.amd64fre.19h1_release.190318-1202",
                "hostname": "DESKTOP-DKQNVC5",
                "memory": {
                    "physical": 16541581312,
                    "swap": 19628589056
                },
                "name": "Windows 10 Pro"
            }
        },
        "version": 2
    }
}
`

**Comment by takskazatsootvetstvenno** [comment] 2022-03-13 09:30
Hi!
I have the same problem with RDP.
[log.txt](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/files/8239254/log.txt)
![image](https://user-images.githubusercontent.com/47656611/158053306-a294fc49-bb42-4184-a422-ba485802f307.png)

**Comment by chesik-amd** [comment] 2022-04-21 18:47
We've released a new version of RGP (v1.13) and RDP (v2.6) today.  This issue should be resolved with the new RDP build (see https://github.com/GPUOpen-Tools/radeon_developer_panel/issues/15).  Can you try the new release and let us know if things work better?

**Comment by delphifirst** [comment] 2022-04-22 02:04
I tried the new version of RGP (v1.13) and RDP (v2.6), and got the same result. RDP crashed immediately when launching application. Here is the new log file.
[log.txt](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/files/8536288/log.txt)

and debug log.
![image](https://user-images.githubusercontent.com/5230702/164581958-5f88ed3b-c34f-49ab-adf6-3a47ef1aad36.png)

**Comment by takskazatsootvetstvenno** [comment] 2022-04-22 16:07
I tried the new version and i got the same problem.
Log:
[log.txt](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/files/8542402/log.txt)

![image](https://user-images.githubusercontent.com/47656611/164752597-7a6184a5-921c-4d7a-8dbd-02b66ef775b8.png)

**Comment by dcheo6** [comment] 2022-05-11 06:42
I have tried the new version "RadeonDeveloperToolSuite-2022-04-20-920", but get the same crash.
In my case, "RadeonDeveloperToolSuite-2020-11-19-376" is the only version working in my PC(5700XT),
By the way, both version don't show the system info either.

**Comment by RandomShaper** [comment] 2022-05-31 11:00
Same here. Spanish-located Windows 10. V1.11 is the most recent one that works.

**Comment by chesik-amd** [comment] 2022-05-31 16:55
This is a problem with the Radeon Developer Panel and is currently being tracked here: https://github.com/GPUOpen-Tools/radeon_developer_panel/issues/15

**Comment by chesik-amd** [comment] 2022-12-14 19:58
This has been addressed in the latest release.  See https://github.com/GPUOpen-Tools/radeon_developer_panel/issues/15

**Closed by chesik-amd** 2022-12-14 19:58 UTC
Labels: duplicate

**Comment by RandomShaper** [comment] 2022-12-14 20:19
Confirmed as fixed for me.
