### ISSUE TITLE
capture from app start

### ISSUE THREAD

**Issue by pemgithub** [GPUOpen-Tools/radeon_gpu_profiler#34] opened 2019-11-27 22:42 UTC
There should be an option to capture an RGP profile from app start, or from a particular frame.  That way you can consistently run the same frame, eg to optimize an API trace or benchmark.

**Comment by chesik-amd** [comment] 2020-09-15 13:06
This is a duplicate of https://github.com/GPUOpen-Tools/radeon_gpu_profiler/issues/13

**Closed by chesik-amd** 2020-09-15 13:06 UTC
